alias(
    name = "agent-computer",
    actual = "//crates/cli:agent-computer",
    visibility = ["//visibility:public"],
)

exports_files(["rust-toolchain.toml", "Cargo.toml", "Cargo.lock"])

alias(
    name = "agent-computer-server",
    actual = "//crates/server:agent-computer-server",
    visibility = ["//visibility:public"],
)
